import React, { useState } from 'react';
import { ChevronDown, HelpCircle, ShieldCheck } from 'lucide-react';

interface FaqItem {
  question: string;
  answer: string;
}

const FAQS: FaqItem[] = [
  {
    question: 'Are my images uploaded to any remote server or cloud database?',
    answer:
      'No. ImageToolBox runs 100% locally in your web browser using HTML5 Canvas, File API, and Blob APIs. Your photos never leave your computer or phone, which ensures maximum confidentiality, instant processing, and zero privacy leakage.',
  },
  {
    question: 'Is ImageToolBox completely free to use?',
    answer:
      'Yes, ImageToolBox is completely free for personal and commercial usage with no registration, no subscription fees, no watermarks, and no hidden file quotas.',
  },
  {
    question: 'Which image formats are supported?',
    answer:
      'You can load and convert popular web image formats including JPG / JPEG, PNG, WebP, SVG, BMP, ICO, and GIF.',
  },
  {
    question: 'How does the Image Compressor reduce file size without losing quality?',
    answer:
      'The compressor employs high-performance browser-native lossy and lossless canvas encoding algorithms, eliminating redundant metadata and optimizing color quantization while allowing you to dial in the exact compression level in real time.',
  },
  {
    question: 'Can I use ImageToolBox on mobile phones and tablets?',
    answer:
      'Yes! ImageToolBox is designed mobile-first and optimized for iPhone and Android screens (including 375px–430px viewports) with fluid touch controls and responsive layouts.',
  },
  {
    question: 'What are the dimensions generated by the Favicon Generator?',
    answer:
      'The Favicon Generator produces the standard web suite: 16×16 px (browser tabs), 32×32 px (high-DPI bookmark bars), 48×48 px (desktop shortcuts), and 180×180 px (Apple Touch Icons for iOS home screens), alongside clean HTML embed snippet code.',
  },
];

export const FaqSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggle = (i: number) => {
    setOpenIndex(openIndex === i ? null : i);
  };

  return (
    <section id="faq" className="py-12 sm:py-16 border-t border-zinc-100 dark:border-zinc-900">
      <div className="max-w-4xl mx-auto px-4 sm:px-6">
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-100 dark:bg-amber-950/60 text-amber-900 dark:text-amber-300 text-xs font-semibold mb-3">
            <HelpCircle className="w-3.5 h-3.5 text-amber-600 dark:text-amber-400" />
            <span>Got Questions?</span>
          </div>
          <h2 className="text-2xl sm:text-4xl font-black text-zinc-950 dark:text-white">
            Frequently Asked Questions
          </h2>
          <p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">
            Everything you need to know about our private in-browser image suite
          </p>
        </div>

        <div className="space-y-3">
          {FAQS.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div
                key={faq.question}
                className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/60 overflow-hidden transition-colors"
              >
                <button
                  onClick={() => toggle(index)}
                  className="w-full p-4 sm:p-5 text-left flex items-center justify-between gap-4 font-bold text-sm sm:text-base text-zinc-900 dark:text-white hover:text-amber-600 dark:hover:text-amber-400 transition-colors"
                >
                  <span>{faq.question}</span>
                  <div
                    className={`w-7 h-7 rounded-full bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center shrink-0 transition-transform duration-200 ${
                      isOpen ? 'rotate-180 bg-amber-400 text-zinc-950' : 'text-zinc-500'
                    }`}
                  >
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-4 pb-5 sm:px-5 text-xs sm:text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed border-t border-zinc-100 dark:border-zinc-800/80 pt-3">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};
